[build]
builder = "NIXPACKS"
buildCommand = "cd backend && ./mvnw clean package -DskipTests"
startCommand = "cd backend && java -jar target/*.jar"

[deploy]
startCommand = "cd backend && java -jar target/*.jar"
