[phases.setup]
nixPkgs = ["jdk17", "maven"]

[build]
builder = "nixpacks"
buildCommand = "chmod +x backend/mvnw && cd backend && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -jar target/*.jar"
