[phases.setup]
nixPkgs = ["jdk21", "maven"]


[build]
builder = "nixpacks"
buildCommand = "chmod +x backend/mvnw && export JAVA_HOME=$(dirname $(dirname $(which java))) && ./backend/mvnw -f backend/pom.xml clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -jar target/*.jar"
