[phases.setup]
nixPkgs = ["jdk21", "maven"]

[build]
builder = "nixpacks"
buildCommand = "chmod +x backend/mvnw && ./backend/mvnw -f backend/pom.xml clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -jar target/*.jar"
